[package]
name = "bitcoin-indexer"
version = "0.1.5"
edition = "2021"
description = "Bitcoin indexer"
keywords = ["bitcoin", "indexer"]
homepage = "https://github.com/FairgateLabs/rust-bitcoin-indexer"
repository = "https://github.com/FairgateLabs/rust-bitcoin-indexer"
readme = "README.md"


[dependencies]
bitcoin = "0.32.2"
bitcoincore-rpc = "0.19"
log = "0.4"
env_logger = { version = "*", default-features = false, features = [
  "termcolor",
  "atty",
  "humantime",
] }
dotenv = "0.15"
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
mockall = "0.13.0"
postgres = "0.19.1"
url = "2.5.2"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0"
bitcoin_hashes = "0.15"
hex = "0.4.3"
ctrlc = "3.4"
rust-bitvmx-storage-backend = { path = "../rust-bitvmx-storage-backend" }
